import cv2

SEE_COUNTOURS = True
SEE_COUNTOURS_TIME = 1000

SEE_DIGIT = True
SEE_DIGIT_TIME = 10

DIGIT_SIZE = 60
FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 1.5
FONT_THICKNESS = 4
FONT_COLOR = (255, 0, 0)
TEMPORARY_FONT_COLOR = (0, 0, 255)
FONT_LINE_TYPE = cv2.LINE_AA
